import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

interface OpenGraphVideoMovie {
  actors?: string[];
  directors?: string[];
  writers?: string[];
  duration?: number;
  releaseDate?: string;
  tags?: string[];
  type: 'video.movie';
}
export interface OpenGraphVideoTVShow extends Omit<OpenGraphVideoMovie, 'type'> {
  type: 'video.tv_show';
}

export interface OpenGraphVideoOther extends Omit<OpenGraphVideoMovie, 'type'> {
  type: 'video.other';
}


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph:{
    type: 'video.tv_show',
    actors: ['Actor One', 'Actor Two']
  }as OpenGraphVideoTVShow,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
